apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '9157'
    prometheus.io/scrape: 'true'
  name: mq-prometheus
  labels:
    app.kubernetes.io/name: __qmgrname__-ibm-mq-metrics
spec:
  selector:
    app.kubernetes.io/instance: __qmgrname__-qm
  ports:
    - name: metrics
      protocol: TCP
      port: 9157
      targetPort: 9157

