apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
 disableNameSuffixHash: true

# Create a configMap that holds scripts for the queue manager service.
configMapGenerator:

- name: scripts-configmap
  behavior: create
  files:
  - start-mqsc.sh
  - stop-mqsc.sh
